//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace first_web_server.external_helpdesk_ev {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExternalHelpdeskDataContract", Namespace="http://schema.evatic.com/2012/10/24")]
    [System.SerializableAttribute()]
    public partial class ExternalHelpdeskDataContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionCode1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionCode2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionCode3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid CustomerGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EventStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalCustomerNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExternalProjectNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ExternalSystemGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExternalTaskNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InternalCommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> MachineGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MachineNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> MaxActiveFromWField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> MinActiveFromWField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> OnHoldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private first_web_server.external_helpdesk_ev.ExternalHelpdeskTaskPreOrderDataContract[] PreOrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProjectNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ReciveDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ResponseDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResponseTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SolutionDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SolutionTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SymptomCode1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SymptomCode2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SymptomCode3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SymptomTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid TaskGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TaskNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActionCode1 {
            get {
                return this.ActionCode1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ActionCode1Field, value) != true)) {
                    this.ActionCode1Field = value;
                    this.RaisePropertyChanged("ActionCode1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActionCode2 {
            get {
                return this.ActionCode2Field;
            }
            set {
                if ((object.ReferenceEquals(this.ActionCode2Field, value) != true)) {
                    this.ActionCode2Field = value;
                    this.RaisePropertyChanged("ActionCode2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActionCode3 {
            get {
                return this.ActionCode3Field;
            }
            set {
                if ((object.ReferenceEquals(this.ActionCode3Field, value) != true)) {
                    this.ActionCode3Field = value;
                    this.RaisePropertyChanged("ActionCode3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActionText {
            get {
                return this.ActionTextField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionTextField, value) != true)) {
                    this.ActionTextField = value;
                    this.RaisePropertyChanged("ActionText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CustomerGuid {
            get {
                return this.CustomerGuidField;
            }
            set {
                if ((this.CustomerGuidField.Equals(value) != true)) {
                    this.CustomerGuidField = value;
                    this.RaisePropertyChanged("CustomerGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerNo {
            get {
                return this.CustomerNoField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNoField, value) != true)) {
                    this.CustomerNoField = value;
                    this.RaisePropertyChanged("CustomerNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EventStatus {
            get {
                return this.EventStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.EventStatusField, value) != true)) {
                    this.EventStatusField = value;
                    this.RaisePropertyChanged("EventStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalCustomerNo {
            get {
                return this.ExternalCustomerNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalCustomerNoField, value) != true)) {
                    this.ExternalCustomerNoField = value;
                    this.RaisePropertyChanged("ExternalCustomerNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExternalProjectNo {
            get {
                return this.ExternalProjectNoField;
            }
            set {
                if ((this.ExternalProjectNoField.Equals(value) != true)) {
                    this.ExternalProjectNoField = value;
                    this.RaisePropertyChanged("ExternalProjectNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ExternalSystemGuid {
            get {
                return this.ExternalSystemGuidField;
            }
            set {
                if ((this.ExternalSystemGuidField.Equals(value) != true)) {
                    this.ExternalSystemGuidField = value;
                    this.RaisePropertyChanged("ExternalSystemGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExternalTaskNo {
            get {
                return this.ExternalTaskNoField;
            }
            set {
                if ((this.ExternalTaskNoField.Equals(value) != true)) {
                    this.ExternalTaskNoField = value;
                    this.RaisePropertyChanged("ExternalTaskNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InternalComment {
            get {
                return this.InternalCommentField;
            }
            set {
                if ((object.ReferenceEquals(this.InternalCommentField, value) != true)) {
                    this.InternalCommentField = value;
                    this.RaisePropertyChanged("InternalComment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> MachineGuid {
            get {
                return this.MachineGuidField;
            }
            set {
                if ((this.MachineGuidField.Equals(value) != true)) {
                    this.MachineGuidField = value;
                    this.RaisePropertyChanged("MachineGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MachineNo {
            get {
                return this.MachineNoField;
            }
            set {
                if ((object.ReferenceEquals(this.MachineNoField, value) != true)) {
                    this.MachineNoField = value;
                    this.RaisePropertyChanged("MachineNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> MaxActiveFromW {
            get {
                return this.MaxActiveFromWField;
            }
            set {
                if ((this.MaxActiveFromWField.Equals(value) != true)) {
                    this.MaxActiveFromWField = value;
                    this.RaisePropertyChanged("MaxActiveFromW");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> MinActiveFromW {
            get {
                return this.MinActiveFromWField;
            }
            set {
                if ((this.MinActiveFromWField.Equals(value) != true)) {
                    this.MinActiveFromWField = value;
                    this.RaisePropertyChanged("MinActiveFromW");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Node {
            get {
                return this.NodeField;
            }
            set {
                if ((object.ReferenceEquals(this.NodeField, value) != true)) {
                    this.NodeField = value;
                    this.RaisePropertyChanged("Node");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> OnHold {
            get {
                return this.OnHoldField;
            }
            set {
                if ((this.OnHoldField.Equals(value) != true)) {
                    this.OnHoldField = value;
                    this.RaisePropertyChanged("OnHold");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public first_web_server.external_helpdesk_ev.ExternalHelpdeskTaskPreOrderDataContract[] PreOrder {
            get {
                return this.PreOrderField;
            }
            set {
                if ((object.ReferenceEquals(this.PreOrderField, value) != true)) {
                    this.PreOrderField = value;
                    this.RaisePropertyChanged("PreOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProjectNo {
            get {
                return this.ProjectNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectNoField, value) != true)) {
                    this.ProjectNoField = value;
                    this.RaisePropertyChanged("ProjectNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ReciveDate {
            get {
                return this.ReciveDateField;
            }
            set {
                if ((this.ReciveDateField.Equals(value) != true)) {
                    this.ReciveDateField = value;
                    this.RaisePropertyChanged("ReciveDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ResponseDate {
            get {
                return this.ResponseDateField;
            }
            set {
                if ((this.ResponseDateField.Equals(value) != true)) {
                    this.ResponseDateField = value;
                    this.RaisePropertyChanged("ResponseDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResponseTime {
            get {
                return this.ResponseTimeField;
            }
            set {
                if ((this.ResponseTimeField.Equals(value) != true)) {
                    this.ResponseTimeField = value;
                    this.RaisePropertyChanged("ResponseTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SolutionDate {
            get {
                return this.SolutionDateField;
            }
            set {
                if ((this.SolutionDateField.Equals(value) != true)) {
                    this.SolutionDateField = value;
                    this.RaisePropertyChanged("SolutionDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SolutionTime {
            get {
                return this.SolutionTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.SolutionTimeField, value) != true)) {
                    this.SolutionTimeField = value;
                    this.RaisePropertyChanged("SolutionTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SymptomCode1 {
            get {
                return this.SymptomCode1Field;
            }
            set {
                if ((object.ReferenceEquals(this.SymptomCode1Field, value) != true)) {
                    this.SymptomCode1Field = value;
                    this.RaisePropertyChanged("SymptomCode1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SymptomCode2 {
            get {
                return this.SymptomCode2Field;
            }
            set {
                if ((object.ReferenceEquals(this.SymptomCode2Field, value) != true)) {
                    this.SymptomCode2Field = value;
                    this.RaisePropertyChanged("SymptomCode2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SymptomCode3 {
            get {
                return this.SymptomCode3Field;
            }
            set {
                if ((object.ReferenceEquals(this.SymptomCode3Field, value) != true)) {
                    this.SymptomCode3Field = value;
                    this.RaisePropertyChanged("SymptomCode3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SymptomText {
            get {
                return this.SymptomTextField;
            }
            set {
                if ((object.ReferenceEquals(this.SymptomTextField, value) != true)) {
                    this.SymptomTextField = value;
                    this.RaisePropertyChanged("SymptomText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid TaskGuid {
            get {
                return this.TaskGuidField;
            }
            set {
                if ((this.TaskGuidField.Equals(value) != true)) {
                    this.TaskGuidField = value;
                    this.RaisePropertyChanged("TaskGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaskNo {
            get {
                return this.TaskNoField;
            }
            set {
                if ((object.ReferenceEquals(this.TaskNoField, value) != true)) {
                    this.TaskNoField = value;
                    this.RaisePropertyChanged("TaskNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExternalHelpdeskTaskPreOrderDataContract", Namespace="http://schemas.datacontract.org/2004/07/Evatic.Common.Service.DataContract.Extern" +
        "alHelpdesk")]
    [System.SerializableAttribute()]
    public partial class ExternalHelpdeskTaskPreOrderDataContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArticleNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StockNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArticleNo {
            get {
                return this.ArticleNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ArticleNoField, value) != true)) {
                    this.ArticleNoField = value;
                    this.RaisePropertyChanged("ArticleNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Number {
            get {
                return this.NumberField;
            }
            set {
                if ((this.NumberField.Equals(value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StockNo {
            get {
                return this.StockNoField;
            }
            set {
                if ((object.ReferenceEquals(this.StockNoField, value) != true)) {
                    this.StockNoField = value;
                    this.RaisePropertyChanged("StockNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExternalHelpdeskCreateOrUpdateRequestDataContract", Namespace="http://schema.evatic.com/2012/10/24")]
    [System.SerializableAttribute()]
    public partial class ExternalHelpdeskCreateOrUpdateRequestDataContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactPhoneNummberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> CustomerGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ExternalCreateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalCustomerNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalProjectNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ExternalSystemGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalTaskNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Information1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Information2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Information3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Information4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Information5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Information6Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InternalCommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> MachineGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MachineModelTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MachineNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private first_web_server.external_helpdesk_ev.ExternalHelpdeskTaskPreOrderDataContract[] PreOrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PriorityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceivedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ReceviedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ResonseDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResonseTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> SolutionDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SymptomCode1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SymptomCode2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SymptomCode3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SymptomCode4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SymptomTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid TaskGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactEmail {
            get {
                return this.ContactEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactEmailField, value) != true)) {
                    this.ContactEmailField = value;
                    this.RaisePropertyChanged("ContactEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactName {
            get {
                return this.ContactNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactNameField, value) != true)) {
                    this.ContactNameField = value;
                    this.RaisePropertyChanged("ContactName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactPhoneNummber {
            get {
                return this.ContactPhoneNummberField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactPhoneNummberField, value) != true)) {
                    this.ContactPhoneNummberField = value;
                    this.RaisePropertyChanged("ContactPhoneNummber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> CustomerGuid {
            get {
                return this.CustomerGuidField;
            }
            set {
                if ((this.CustomerGuidField.Equals(value) != true)) {
                    this.CustomerGuidField = value;
                    this.RaisePropertyChanged("CustomerGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ExternalCreateDate {
            get {
                return this.ExternalCreateDateField;
            }
            set {
                if ((this.ExternalCreateDateField.Equals(value) != true)) {
                    this.ExternalCreateDateField = value;
                    this.RaisePropertyChanged("ExternalCreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalCustomerNo {
            get {
                return this.ExternalCustomerNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalCustomerNoField, value) != true)) {
                    this.ExternalCustomerNoField = value;
                    this.RaisePropertyChanged("ExternalCustomerNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalProjectNo {
            get {
                return this.ExternalProjectNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalProjectNoField, value) != true)) {
                    this.ExternalProjectNoField = value;
                    this.RaisePropertyChanged("ExternalProjectNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ExternalSystemGuid {
            get {
                return this.ExternalSystemGuidField;
            }
            set {
                if ((this.ExternalSystemGuidField.Equals(value) != true)) {
                    this.ExternalSystemGuidField = value;
                    this.RaisePropertyChanged("ExternalSystemGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalTaskNo {
            get {
                return this.ExternalTaskNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalTaskNoField, value) != true)) {
                    this.ExternalTaskNoField = value;
                    this.RaisePropertyChanged("ExternalTaskNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Information1 {
            get {
                return this.Information1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Information1Field, value) != true)) {
                    this.Information1Field = value;
                    this.RaisePropertyChanged("Information1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Information2 {
            get {
                return this.Information2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Information2Field, value) != true)) {
                    this.Information2Field = value;
                    this.RaisePropertyChanged("Information2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Information3 {
            get {
                return this.Information3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Information3Field, value) != true)) {
                    this.Information3Field = value;
                    this.RaisePropertyChanged("Information3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Information4 {
            get {
                return this.Information4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Information4Field, value) != true)) {
                    this.Information4Field = value;
                    this.RaisePropertyChanged("Information4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Information5 {
            get {
                return this.Information5Field;
            }
            set {
                if ((object.ReferenceEquals(this.Information5Field, value) != true)) {
                    this.Information5Field = value;
                    this.RaisePropertyChanged("Information5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Information6 {
            get {
                return this.Information6Field;
            }
            set {
                if ((object.ReferenceEquals(this.Information6Field, value) != true)) {
                    this.Information6Field = value;
                    this.RaisePropertyChanged("Information6");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InternalComment {
            get {
                return this.InternalCommentField;
            }
            set {
                if ((object.ReferenceEquals(this.InternalCommentField, value) != true)) {
                    this.InternalCommentField = value;
                    this.RaisePropertyChanged("InternalComment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> MachineGuid {
            get {
                return this.MachineGuidField;
            }
            set {
                if ((this.MachineGuidField.Equals(value) != true)) {
                    this.MachineGuidField = value;
                    this.RaisePropertyChanged("MachineGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MachineModelType {
            get {
                return this.MachineModelTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.MachineModelTypeField, value) != true)) {
                    this.MachineModelTypeField = value;
                    this.RaisePropertyChanged("MachineModelType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MachineNo {
            get {
                return this.MachineNoField;
            }
            set {
                if ((object.ReferenceEquals(this.MachineNoField, value) != true)) {
                    this.MachineNoField = value;
                    this.RaisePropertyChanged("MachineNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public first_web_server.external_helpdesk_ev.ExternalHelpdeskTaskPreOrderDataContract[] PreOrder {
            get {
                return this.PreOrderField;
            }
            set {
                if ((object.ReferenceEquals(this.PreOrderField, value) != true)) {
                    this.PreOrderField = value;
                    this.RaisePropertyChanged("PreOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Priority {
            get {
                return this.PriorityField;
            }
            set {
                if ((object.ReferenceEquals(this.PriorityField, value) != true)) {
                    this.PriorityField = value;
                    this.RaisePropertyChanged("Priority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceivedBy {
            get {
                return this.ReceivedByField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceivedByField, value) != true)) {
                    this.ReceivedByField = value;
                    this.RaisePropertyChanged("ReceivedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ReceviedDate {
            get {
                return this.ReceviedDateField;
            }
            set {
                if ((this.ReceviedDateField.Equals(value) != true)) {
                    this.ReceviedDateField = value;
                    this.RaisePropertyChanged("ReceviedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ResonseDate {
            get {
                return this.ResonseDateField;
            }
            set {
                if ((this.ResonseDateField.Equals(value) != true)) {
                    this.ResonseDateField = value;
                    this.RaisePropertyChanged("ResonseDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResonseTime {
            get {
                return this.ResonseTimeField;
            }
            set {
                if ((this.ResonseTimeField.Equals(value) != true)) {
                    this.ResonseTimeField = value;
                    this.RaisePropertyChanged("ResonseTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SolutionDate {
            get {
                return this.SolutionDateField;
            }
            set {
                if ((this.SolutionDateField.Equals(value) != true)) {
                    this.SolutionDateField = value;
                    this.RaisePropertyChanged("SolutionDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SymptomCode1 {
            get {
                return this.SymptomCode1Field;
            }
            set {
                if ((object.ReferenceEquals(this.SymptomCode1Field, value) != true)) {
                    this.SymptomCode1Field = value;
                    this.RaisePropertyChanged("SymptomCode1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SymptomCode2 {
            get {
                return this.SymptomCode2Field;
            }
            set {
                if ((object.ReferenceEquals(this.SymptomCode2Field, value) != true)) {
                    this.SymptomCode2Field = value;
                    this.RaisePropertyChanged("SymptomCode2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SymptomCode3 {
            get {
                return this.SymptomCode3Field;
            }
            set {
                if ((object.ReferenceEquals(this.SymptomCode3Field, value) != true)) {
                    this.SymptomCode3Field = value;
                    this.RaisePropertyChanged("SymptomCode3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SymptomCode4 {
            get {
                return this.SymptomCode4Field;
            }
            set {
                if ((object.ReferenceEquals(this.SymptomCode4Field, value) != true)) {
                    this.SymptomCode4Field = value;
                    this.RaisePropertyChanged("SymptomCode4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SymptomText {
            get {
                return this.SymptomTextField;
            }
            set {
                if ((object.ReferenceEquals(this.SymptomTextField, value) != true)) {
                    this.SymptomTextField = value;
                    this.RaisePropertyChanged("SymptomText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid TaskGuid {
            get {
                return this.TaskGuidField;
            }
            set {
                if ((this.TaskGuidField.Equals(value) != true)) {
                    this.TaskGuidField = value;
                    this.RaisePropertyChanged("TaskGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titel {
            get {
                return this.TitelField;
            }
            set {
                if ((object.ReferenceEquals(this.TitelField, value) != true)) {
                    this.TitelField = value;
                    this.RaisePropertyChanged("Titel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExternalHelpdeskCreateOrUpdateResponseDataContract", Namespace="http://schema.evatic.com/2012/10/24")]
    [System.SerializableAttribute()]
    public partial class ExternalHelpdeskCreateOrUpdateResponseDataContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalProjectNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ExternalSystemGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalTaskNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProjectStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProjectTaskNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> TaskGuidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerNo {
            get {
                return this.CustomerNoField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNoField, value) != true)) {
                    this.CustomerNoField = value;
                    this.RaisePropertyChanged("CustomerNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalProjectNo {
            get {
                return this.ExternalProjectNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalProjectNoField, value) != true)) {
                    this.ExternalProjectNoField = value;
                    this.RaisePropertyChanged("ExternalProjectNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ExternalSystemGuid {
            get {
                return this.ExternalSystemGuidField;
            }
            set {
                if ((this.ExternalSystemGuidField.Equals(value) != true)) {
                    this.ExternalSystemGuidField = value;
                    this.RaisePropertyChanged("ExternalSystemGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalTaskNo {
            get {
                return this.ExternalTaskNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalTaskNoField, value) != true)) {
                    this.ExternalTaskNoField = value;
                    this.RaisePropertyChanged("ExternalTaskNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProjectStatus {
            get {
                return this.ProjectStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectStatusField, value) != true)) {
                    this.ProjectStatusField = value;
                    this.RaisePropertyChanged("ProjectStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProjectTaskNo {
            get {
                return this.ProjectTaskNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectTaskNoField, value) != true)) {
                    this.ProjectTaskNoField = value;
                    this.RaisePropertyChanged("ProjectTaskNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseMessage {
            get {
                return this.ResponseMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseMessageField, value) != true)) {
                    this.ResponseMessageField = value;
                    this.RaisePropertyChanged("ResponseMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> TaskGuid {
            get {
                return this.TaskGuidField;
            }
            set {
                if ((this.TaskGuidField.Equals(value) != true)) {
                    this.TaskGuidField = value;
                    this.RaisePropertyChanged("TaskGuid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExternalHelpdeskTriggerEventsDataContract", Namespace="http://schema.evatic.com/2012/10/24")]
    [System.SerializableAttribute()]
    public partial class ExternalHelpdeskTriggerEventsDataContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid EventGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EventTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ExternalSystemGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid TaskGuidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid EventGuid {
            get {
                return this.EventGuidField;
            }
            set {
                if ((this.EventGuidField.Equals(value) != true)) {
                    this.EventGuidField = value;
                    this.RaisePropertyChanged("EventGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EventType {
            get {
                return this.EventTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.EventTypeField, value) != true)) {
                    this.EventTypeField = value;
                    this.RaisePropertyChanged("EventType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ExternalSystemGuid {
            get {
                return this.ExternalSystemGuidField;
            }
            set {
                if ((this.ExternalSystemGuidField.Equals(value) != true)) {
                    this.ExternalSystemGuidField = value;
                    this.RaisePropertyChanged("ExternalSystemGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid TaskGuid {
            get {
                return this.TaskGuidField;
            }
            set {
                if ((this.TaskGuidField.Equals(value) != true)) {
                    this.TaskGuidField = value;
                    this.RaisePropertyChanged("TaskGuid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentBaseDataContract", Namespace="http://schema.evatic.com/2012/10/24")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(first_web_server.external_helpdesk_ev.ExternalHelpdeskInsertDocumentRequestDataContract))]
    public partial class DocumentBaseDataContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateCreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid DocumentGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> DocumentSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateCreated {
            get {
                return this.DateCreatedField;
            }
            set {
                if ((this.DateCreatedField.Equals(value) != true)) {
                    this.DateCreatedField = value;
                    this.RaisePropertyChanged("DateCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid DocumentGuid {
            get {
                return this.DocumentGuidField;
            }
            set {
                if ((this.DocumentGuidField.Equals(value) != true)) {
                    this.DocumentGuidField = value;
                    this.RaisePropertyChanged("DocumentGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> DocumentSize {
            get {
                return this.DocumentSizeField;
            }
            set {
                if ((this.DocumentSizeField.Equals(value) != true)) {
                    this.DocumentSizeField = value;
                    this.RaisePropertyChanged("DocumentSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] File {
            get {
                return this.FileField;
            }
            set {
                if ((object.ReferenceEquals(this.FileField, value) != true)) {
                    this.FileField = value;
                    this.RaisePropertyChanged("File");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExternalHelpdeskInsertDocumentRequestDataContract", Namespace="http://schema.evatic.com/2012/10/24")]
    [System.SerializableAttribute()]
    public partial class ExternalHelpdeskInsertDocumentRequestDataContract : first_web_server.external_helpdesk_ev.DocumentBaseDataContract {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalProjectNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ExternalSystemGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid TaskGuidField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalProjectNo {
            get {
                return this.ExternalProjectNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalProjectNoField, value) != true)) {
                    this.ExternalProjectNoField = value;
                    this.RaisePropertyChanged("ExternalProjectNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ExternalSystemGuid {
            get {
                return this.ExternalSystemGuidField;
            }
            set {
                if ((this.ExternalSystemGuidField.Equals(value) != true)) {
                    this.ExternalSystemGuidField = value;
                    this.RaisePropertyChanged("ExternalSystemGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid TaskGuid {
            get {
                return this.TaskGuidField;
            }
            set {
                if ((this.TaskGuidField.Equals(value) != true)) {
                    this.TaskGuidField = value;
                    this.RaisePropertyChanged("TaskGuid");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExternalHelpdeskInsertDocumentResponseDataContract", Namespace="http://schema.evatic.com/2012/10/24")]
    [System.SerializableAttribute()]
    public partial class ExternalHelpdeskInsertDocumentResponseDataContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> DocumentGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> TaskGuidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> DocumentGuid {
            get {
                return this.DocumentGuidField;
            }
            set {
                if ((this.DocumentGuidField.Equals(value) != true)) {
                    this.DocumentGuidField = value;
                    this.RaisePropertyChanged("DocumentGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseMessage {
            get {
                return this.ResponseMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseMessageField, value) != true)) {
                    this.ResponseMessageField = value;
                    this.RaisePropertyChanged("ResponseMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> TaskGuid {
            get {
                return this.TaskGuidField;
            }
            set {
                if ((this.TaskGuidField.Equals(value) != true)) {
                    this.TaskGuidField = value;
                    this.RaisePropertyChanged("TaskGuid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schema.evatic.com/2012/10/24", ConfigurationName="external_helpdesk_ev.ExternalHelpdeskService")]
    public interface ExternalHelpdeskService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schema.evatic.com/2012/10/24/ExternalHelpdeskService/Echo", ReplyAction="http://schema.evatic.com/2012/10/24/ExternalHelpdeskService/EchoResponse")]
        string Echo(string textToEcho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schema.evatic.com/2012/10/24/ExternalHelpdeskService/Echo", ReplyAction="http://schema.evatic.com/2012/10/24/ExternalHelpdeskService/EchoResponse")]
        System.Threading.Tasks.Task<string> EchoAsync(string textToEcho);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schema.evatic.com/2012/10/24/ExternalHelpdeskService/Get", ReplyAction="http://schema.evatic.com/2012/10/24/ExternalHelpdeskService/GetResponse")]
        first_web_server.external_helpdesk_ev.ExternalHelpdeskDataContract Get(System.Guid taskGuid, System.Guid externalSystemGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schema.evatic.com/2012/10/24/ExternalHelpdeskService/Get", ReplyAction="http://schema.evatic.com/2012/10/24/ExternalHelpdeskService/GetResponse")]
        System.Threading.Tasks.Task<first_web_server.external_helpdesk_ev.ExternalHelpdeskDataContract> GetAsync(System.Guid taskGuid, System.Guid externalSystemGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schema.evatic.com/2012/10/24/ExternalHelpdeskService/CreateOrUpdate", ReplyAction="http://schema.evatic.com/2012/10/24/ExternalHelpdeskService/CreateOrUpdateRespons" +
            "e")]
        first_web_server.external_helpdesk_ev.ExternalHelpdeskCreateOrUpdateResponseDataContract CreateOrUpdate(first_web_server.external_helpdesk_ev.ExternalHelpdeskCreateOrUpdateRequestDataContract projectTask);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schema.evatic.com/2012/10/24/ExternalHelpdeskService/CreateOrUpdate", ReplyAction="http://schema.evatic.com/2012/10/24/ExternalHelpdeskService/CreateOrUpdateRespons" +
            "e")]
        System.Threading.Tasks.Task<first_web_server.external_helpdesk_ev.ExternalHelpdeskCreateOrUpdateResponseDataContract> CreateOrUpdateAsync(first_web_server.external_helpdesk_ev.ExternalHelpdeskCreateOrUpdateRequestDataContract projectTask);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schema.evatic.com/2012/10/24/ExternalHelpdeskService/ListTriggerEvents", ReplyAction="http://schema.evatic.com/2012/10/24/ExternalHelpdeskService/ListTriggerEventsResp" +
            "onse")]
        first_web_server.external_helpdesk_ev.ExternalHelpdeskTriggerEventsDataContract[] ListTriggerEvents(System.Guid externalSystemGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schema.evatic.com/2012/10/24/ExternalHelpdeskService/ListTriggerEvents", ReplyAction="http://schema.evatic.com/2012/10/24/ExternalHelpdeskService/ListTriggerEventsResp" +
            "onse")]
        System.Threading.Tasks.Task<first_web_server.external_helpdesk_ev.ExternalHelpdeskTriggerEventsDataContract[]> ListTriggerEventsAsync(System.Guid externalSystemGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schema.evatic.com/2012/10/24/ExternalHelpdeskService/CloseTriggerEvent", ReplyAction="http://schema.evatic.com/2012/10/24/ExternalHelpdeskService/CloseTriggerEventResp" +
            "onse")]
        int CloseTriggerEvent(first_web_server.external_helpdesk_ev.ExternalHelpdeskTriggerEventsDataContract triggerEvent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schema.evatic.com/2012/10/24/ExternalHelpdeskService/CloseTriggerEvent", ReplyAction="http://schema.evatic.com/2012/10/24/ExternalHelpdeskService/CloseTriggerEventResp" +
            "onse")]
        System.Threading.Tasks.Task<int> CloseTriggerEventAsync(first_web_server.external_helpdesk_ev.ExternalHelpdeskTriggerEventsDataContract triggerEvent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schema.evatic.com/2012/10/24/ExternalHelpdeskService/AddDocument", ReplyAction="http://schema.evatic.com/2012/10/24/ExternalHelpdeskService/AddDocumentResponse")]
        first_web_server.external_helpdesk_ev.ExternalHelpdeskInsertDocumentResponseDataContract AddDocument(first_web_server.external_helpdesk_ev.ExternalHelpdeskInsertDocumentRequestDataContract attachment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schema.evatic.com/2012/10/24/ExternalHelpdeskService/AddDocument", ReplyAction="http://schema.evatic.com/2012/10/24/ExternalHelpdeskService/AddDocumentResponse")]
        System.Threading.Tasks.Task<first_web_server.external_helpdesk_ev.ExternalHelpdeskInsertDocumentResponseDataContract> AddDocumentAsync(first_web_server.external_helpdesk_ev.ExternalHelpdeskInsertDocumentRequestDataContract attachment);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ExternalHelpdeskServiceChannel : first_web_server.external_helpdesk_ev.ExternalHelpdeskService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExternalHelpdeskServiceClient : System.ServiceModel.ClientBase<first_web_server.external_helpdesk_ev.ExternalHelpdeskService>, first_web_server.external_helpdesk_ev.ExternalHelpdeskService {
        
        public ExternalHelpdeskServiceClient() {
        }
        
        public ExternalHelpdeskServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExternalHelpdeskServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExternalHelpdeskServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExternalHelpdeskServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Echo(string textToEcho) {
            return base.Channel.Echo(textToEcho);
        }
        
        public System.Threading.Tasks.Task<string> EchoAsync(string textToEcho) {
            return base.Channel.EchoAsync(textToEcho);
        }
        
        public first_web_server.external_helpdesk_ev.ExternalHelpdeskDataContract Get(System.Guid taskGuid, System.Guid externalSystemGuid) {
            return base.Channel.Get(taskGuid, externalSystemGuid);
        }
        
        public System.Threading.Tasks.Task<first_web_server.external_helpdesk_ev.ExternalHelpdeskDataContract> GetAsync(System.Guid taskGuid, System.Guid externalSystemGuid) {
            return base.Channel.GetAsync(taskGuid, externalSystemGuid);
        }
        
        public first_web_server.external_helpdesk_ev.ExternalHelpdeskCreateOrUpdateResponseDataContract CreateOrUpdate(first_web_server.external_helpdesk_ev.ExternalHelpdeskCreateOrUpdateRequestDataContract projectTask) {
            return base.Channel.CreateOrUpdate(projectTask);
        }
        
        public System.Threading.Tasks.Task<first_web_server.external_helpdesk_ev.ExternalHelpdeskCreateOrUpdateResponseDataContract> CreateOrUpdateAsync(first_web_server.external_helpdesk_ev.ExternalHelpdeskCreateOrUpdateRequestDataContract projectTask) {
            return base.Channel.CreateOrUpdateAsync(projectTask);
        }
        
        public first_web_server.external_helpdesk_ev.ExternalHelpdeskTriggerEventsDataContract[] ListTriggerEvents(System.Guid externalSystemGuid) {
            return base.Channel.ListTriggerEvents(externalSystemGuid);
        }
        
        public System.Threading.Tasks.Task<first_web_server.external_helpdesk_ev.ExternalHelpdeskTriggerEventsDataContract[]> ListTriggerEventsAsync(System.Guid externalSystemGuid) {
            return base.Channel.ListTriggerEventsAsync(externalSystemGuid);
        }
        
        public int CloseTriggerEvent(first_web_server.external_helpdesk_ev.ExternalHelpdeskTriggerEventsDataContract triggerEvent) {
            return base.Channel.CloseTriggerEvent(triggerEvent);
        }
        
        public System.Threading.Tasks.Task<int> CloseTriggerEventAsync(first_web_server.external_helpdesk_ev.ExternalHelpdeskTriggerEventsDataContract triggerEvent) {
            return base.Channel.CloseTriggerEventAsync(triggerEvent);
        }
        
        public first_web_server.external_helpdesk_ev.ExternalHelpdeskInsertDocumentResponseDataContract AddDocument(first_web_server.external_helpdesk_ev.ExternalHelpdeskInsertDocumentRequestDataContract attachment) {
            return base.Channel.AddDocument(attachment);
        }
        
        public System.Threading.Tasks.Task<first_web_server.external_helpdesk_ev.ExternalHelpdeskInsertDocumentResponseDataContract> AddDocumentAsync(first_web_server.external_helpdesk_ev.ExternalHelpdeskInsertDocumentRequestDataContract attachment) {
            return base.Channel.AddDocumentAsync(attachment);
        }
    }
}
